name: simpleworld
description: Simmple World Admin Panel


version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <=3.7.12" # ref 4d9e56e

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  cupertino_icons: 1.0.3
  nb_utils: 4.2.8
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  google_fonts: 2.1.0
  flutter_vector_icons: 1.0.0
  cached_network_image: 3.0.0
  intl: 0.17.0
  url_strategy: 0.2.0

  # PUSH NOTIFICATION
  onesignal_flutter: 3.0.0-beta3

  # FIREBASE PACKAGES
  firebase_core: 1.24.0
  firebase_auth: 3.11.2
  cloud_firestore: 3.1.18
  firebase_storage: 10.3.11
  firebase_messaging: 13.1.0
  google_sign_in: 5.0.4
  paginate_firestore: 1.0.3
  timeago: 3.0.2
  flutter_staggered_grid_view: 0.4.0
  url_launcher: 6.0.10
  flutter_linkify: 5.0.2
  link_preview_generator: 1.1.0
  video_player: 2.2.5
  flick_video_player: 0.4.0-dev.4
  string_validator: 0.3.0
  visibility_detector: 0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.0.4
  mobx_codegen: 2.0.1+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  
flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    
    - family: SpaceGrotesk 
      fonts:  
        - asset: assets/fonts/SpaceGrotesk_Regular.ttf
    
    - family: SpaceGroteskbold 
      fonts:  
        - asset: assets/fonts/SpaceGrotesk_Bold.ttf


